### ISSUE TITLE
Support changing which functions are bound

### ISSUE THREAD

**Issue by jkopczyn** [Zopieux/spotify-hotkeys#1]
This is currently possible if you download the source and edit manifest.json, but that requires a) being comfortable doing that, and b) setting Chrome to run in developer mode, which includes incessant nags and probably lowers security.

The extension only appears to supports three functions at once even in dev mode, but I'm not generally a JS or extensions dev so I don't know how immutable that limit is.

**Comment by Zopieux** [comment]
I'm not sure what you mean.

I've disabled Developer mode temporarily and I can still access the extension shortcuts page, where I can customize the shortcuts. You can clear the binding to "disable" a specific control.

![image](https://user-images.githubusercontent.com/81353/82732510-ff34af80-9d0d-11ea-97db-11f9f28b4453.png)

Are you implying you want other controllable buttons? What would they be, then? I'm open to suggestions or PRs.

**Comment by jkopczyn** [comment]
If I open manifest.json, I see that the associations for "liking" a song and some others - I forget which at the moment, I'm on a different computer - are already in the source; making them bindable is a matter of switching which three things are presented as options in the UI.

It is not, however, possible to enable those function from the extension page unless the manifest is modified in that way.

I also found that the screen you show, for editing shortcut bindings, only worked inconsistently. On ChromeOS it works perfectly fine, but on Windows, it was almost never (but not _actually_ never) possible to make any changes to the default shortcuts. The fields were grayed out and did not respond to a click. I never figured out a pattern for when it worked on Windows; after I'd built the extension from source once, I just fixed it by editing the manifest to change the default to what I wanted it to be.

**Comment by Zopieux** [comment]
I've added support for like, repeat & shuffle with no default shortcut though.

Sadly I cannot control what Chrome features work or not depending on your OS. Feel free to report them to upstream. What works for me all the time is to restart Chrome (`chrome://restart`) after I change the shortcuts. I've added these instructions in the README.

**Comment by jkopczyn** [comment]
I don't have that problem with any other extension, so I doubt it's a Chrome thing. Also, again, when it's broken I *can't* change the shortcuts, so your suggestion to use `chrome://restart` is not applicable.
