### ISSUE TITLE
New Spotify design breaks most hotkeys

### ISSUE THREAD

**Issue by yongminparks** [zopieux/spotify-hotkeys#10]
No other hotkeys but only the Next works.

I assume it's due to the recent frontend changes made to the web player.

This is how my control panel looks like atm.

![image](https://user-images.githubusercontent.com/23385272/150647843-2948ac9c-9d85-4abd-8a4c-84c68294cbde.png)

**Comment by zopieux** [comment]
Indeed, thanks for the quick report. Will have a look tomorrow.

**Comment by zopieux** [comment]
@yongminparks You seem to be the lucky winner of some [A/B testing](https://en.wikipedia.org/wiki/A/B_testing) lottery. Spotify does not serve the new UI on my account. I cannot solve this issue unless you dump the HTML structure of your entire play bar in all relevant states. If you are able to and have the time, please use Chrome devtools (F12) to copy/paste (see image) into any pastebin (eg. https://0bin.net/) and give the links here.

You'll need to do **3 copy/pastes** to cover everything:

1. *not liked, not repeating, not shuffled, paused* (your screenshot)
2. *liked, repeating 1, shuffled, playing*
3. any state you like but with *repeating all* enabled

![Untitled](https://user-images.githubusercontent.com/81353/150688981-e6060582-1b11-4fbf-a188-d07dbf21dbac.png)

Thanks for your help!

**Comment by shie1d3d** [comment]
Same issues for me as well:

https://0bin.net/paste/Xj-HwDDv#Ms6KuCx7CjRjANJpi2MxhqZI3Lv0unA8hwsnDz5ufoT
https://0bin.net/paste/+sODMw+6#V3J-8LKCHPgYjBOuJ2AS2QcwkOLZZJufj1kfknP0D5W
https://0bin.net/paste/ouexpaXJ#SuacBBeClrd4AE1ODWsjL2QPJc84I6cadAOiGjdzfLs

Hope that helps!

**Comment by zopieux** [comment]
@shie1d3d Perfect, thanks a lot, that should do it. It's very late here so I'll do that tomorrow.

**Comment by zopieux** [comment]
All right, I sent 0.6.2 for review by Google. Since I cannot test the changes myself, please report back if this issue is actually fixed when you get the update (probably some time tomorrow).

**Comment by yongminparks** [comment]
It's fixed on my end.
Big thanks for the quick fix. I appreciate it a lot.

**Comment by zopieux** [comment]
Thanks for confirming!
