### ISSUE TITLE
spotify web hotkeys and spotify lyrics extensions not working properly together (sometimes)

### ISSUE THREAD

**Issue by TheWondaBoi** [zopieux/spotify-hotkeys#11]
Hello , so basically when i use the LIKE hotkey it works fine for like over 10 songs and then it starts toggling the spotify lyrics pip instead of liking the song 

so what i have to do to make it work normal again is >>> reloading the spotify page and it keeps happening again after listening to few songs and i have to reload page again 

this also happened in pwa spotify and in other browsers like brave , edge 

here is the spotify-lyrics extension (https://github.com/mantou132/Spotify-Lyrics)

here is a picture 
https://i.imgur.com/uhdOVOi.png 

these 2 extensions together make spotify work so good and it is really sad they don't work together properly

**Comment by zopieux** [comment]
Hi there, while I can't promise that I will invest time in supporting the plethora of Spotify extensions that may affect Hot Keys – there are just too many of them – I can try adding a workaround, if you can help me get there though.

1. Does it behave differently between songs that have lyrics available and songs that do not?
1. Would you be able to provide me with the HTML contents of the Spotify bar when you're using the extension? You can do that by following the instructions in [this comment](https://github.com/zopieux/spotify-hotkeys/issues/10#issuecomment-1019523781). I'm looking for a dump when the lyrics are available (but no PIP); as well as when PIP is being used. Thanks.

**Comment by zopieux** [comment]
Oh I see, it would have been helpful to link to the issue you opened in the extension's tracker: https://github.com/mantou132/Spotify-Lyrics/issues/94

It copies the attributes of the like button (https://github.com/mantou132/Spotify-Lyrics/blob/master/src/page/config.json#L12=) for style purposes, which therefore confuses my code.

**Comment by TheWondaBoi** [comment]
so i just run the playlist , keep spotify minimized (as your extension offers global hotkeys which is why i use it) and im able to like , play/pause , next music/previous and with pip lyrics by spoitfy lyrics , without having to pull up spotify window anymore

**Comment by zopieux** [comment]
Please wait until Google accepts version 1.0.0 of the extension, which should automatically get to you in a few days. It should have fixed your issue.
