### ISSUE TITLE
Add volume control hotkeys

### ISSUE THREAD

**Issue by CyanSlinky** [zopieux/spotify-hotkeys#12]
Hey, really good extension. Would it be possible to add hotkeys for volume control?

- Volume Up (Increment volume level by 1)
- Volume Down (Decrement volume level by 1)
- Volume Mute (On/Off toggle)

**Comment by zopieux** [comment]
Hi there, thanks for the kind message. It's a good idea, I've added shortcuts for all three.

Version 1.1.0 was sent for review by Google, it should be available within 24h or so. You'll have to manually assign shortcuts for the new volume commands in your Chrome settings (extension shortcuts), see the README.
