### ISSUE TITLE
Seek Forward/Backward for Music Tracks

### ISSUE THREAD

**Issue by neviln** [zopieux/spotify-hotkeys#13]
Absolutely LOVE this extension since it allows me to globally control Spotify's Web Player without needing to put focus on the tab.

I was really hoping the "Podcast: seek backward" and Podcast: seek forward" shortcut keys would also work for seeking audio tracks but they don't. The Spotify Web Player has it's own built-in shortcut for seeking (Shift + Arrow Left) and (Shift + Arrow Right), but they only work when the tab is active. Is there anyway to request this feature so I can seek tracks globally?

Thank you so much for making this. :)

**Comment by zopieux** [comment]
Thanks for the kind words and suggestion.

I've implemented generalized seek shortcuts (using the same shortcuts as podcasts) in the latest version (1.2.0). Google should review that within the next 24 hours, so watch out for the latest update!

**Comment by neviln** [comment]
WOW! Talk about outstanding response time. I really appreciate you updating the changes so fast. :smile:

**Comment by zopieux** [comment]
I don't always have the time – caught me on a good day. :wink: You're most welcome!
