### ISSUE TITLE
volume control hotkeys broken

### ISSUE THREAD

**Issue by smurfvindaloo** [zopieux/spotify-hotkeys#16]
Hi. Thanks for this terrific extension. As of 16/08 it does not recognise any shortcuts for the volume increase/decrease. Experienced no problems at all prior to this date. Cheers

**Comment by mmeowmeow** [comment]
@zopieux
`[data-testid*=volume]` instead of `[class*=volume]` fixes the issue.

**Comment by smurfvindaloo** [comment]
Many thanks for your insight Nikolay. Was able to modify the extension and get it working again!

**Comment by zopieux** [comment]
Thanks both. Version 1.2.1 is now under review by Google and should it your Chrome soon.
