### ISSUE TITLE
'queue-search' command no longer cycles correctly

### ISSUE THREAD

**Issue by frypf** [zopieux/spotify-hotkeys#17]
Hi again @zopieux,

As per title - I just noticed today that Spotify have changed the way that they display the queue. They no longer populate the window pathname to reflect being on the queue page, instead just showing it in the right sidebar - which means that cycling between the 3 home / queue / search states no longer works. Could've happened a while ago, it's been a while since I last used that shortcut.

I did some (very) quick experimenting, and it's possible to find if the queue is currently shown by appending `"[data-active='true']"` to the existing queue button selector, ie. updating [this if block](https://github.com/zopieux/spotify-hotkeys/blob/55ed81c9acdfd6b544d8765f12b509ff6da1f6e6/src/background.js#L182) seems to return the old functionality:
```js
if (command === 'queue-search') {
  if (document.querySelector("[data-testid='control-button-queue'][data-active='true']")) {
    dispatchCommand('queue');
    command = 'search';
  } else if (window.location.pathname.startsWith('/search')) {
    command = 'home';
  } else {
    command = 'queue';
  }
}
```

Rather than doing a pull request straight away I thought I'd flag it up with you first. Mainly to scope out if you thought it better / easier to just hardcode the active queue button selector into that `if`. Or whether you thought it might be worthwhile going forward to incorporate an additional option to return an element from [`usingSelector()`](https://github.com/zopieux/spotify-hotkeys/blob/55ed81c9acdfd6b544d8765f12b509ff6da1f6e6/src/background.js#L42) (and perhaps also [`usingSvg()`](https://github.com/zopieux/spotify-hotkeys/blob/55ed81c9acdfd6b544d8765f12b509ff6da1f6e6/src/background.js#L64) ), without necessarily clicking it? That way we could query the current state of that button (and potentially others) via classes, dataset attributes, etc. (or whatever else Spotify decide to implement going forward) 🤔.

**Comment by frypf** [comment]
I [had a quick go ](https://github.com/frypf/spotify-hotkeys/tree/working) at testing out the more extensible second approach. Although if I'm honest the cycling thing doesn't really flow so well now that the queue is presented within that side view, so I've also experimented with separating the queue and search commands.

**Comment by zopieux** [comment]
Thanks for sharing your workaround. I've reused some of it for https://github.com/zopieux/spotify-hotkeys/commit/9cb82f40dc50b256ec31062084fbbbf2c7e0fe76 along other changes, crediting you with co-authored-by. Hope that's okay!

**Comment by frypf** [comment]
No probs and thanks for the credit - I wasn't sure that workaround for unlike was all that useful but glad to hear it has been 👍
