### ISSUE TITLE
Hotkeys Playback: seek backward and Playback: seek forward not working  

### ISSUE THREAD

**Issue by Wallcroft24** [zopieux/spotify-hotkeys#18]
Hello I habben problems ago few month with the; "Playback: seek backward" and "Playback: seek forward" and try assigning them to other keys or try with another browser, such as Opera gx and Microsoft Edge.

 It should be noted that I am a user without programming knowledge.
 
 I would like to know if there is a solution to this, I await your response.

**Comment by zopieux** [comment]
Thanks @Wallcroft24, this is fixed in the latest version (v1.4.1) which will be automatically retrieved by your Chrome once Google reviews it, 1-2 days from now.
