### ISSUE TITLE
Toggle repeat does not work for me

### ISSUE THREAD

**Issue by msp26** [Zopieux/spotify-hotkeys#3]
I tried a few different hotkeys out and was unable to get repeat working. Rest works fine.
Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by Zopieux** [comment]
Thanks for the report. Spotify changed its code, I've pushed a new release with the fix. It's being reviewed by Google.

**Comment by Zopieux** [comment]
Version 0.5.0 is now live.
