### ISSUE TITLE
Doesn't Work on Incognito Window.-

### ISSUE THREAD

**Issue by FranHered** [Zopieux/spotify-hotkeys#4]
Hi Alexandre!
Finally I've found an extension that actually works (all the others I've tried stopped working almost two months ago), but only in the default chrome window. When I use the Incognito window it just won't work although it has permission to read it from the extension options.

![image](https://user-images.githubusercontent.com/78547996/106907303-deb25700-66dc-11eb-9183-9908e4854fc9.png)

**Comment by Zopieux** [comment]
Hello @FranHered, thanks for the report, glad this is useful to you.

Have you tried running Spotify Web *only* in the incognito window, closing the non-incognito windows? Does it work in that case?

I haven't looked too closely, but my guess is that Chrome does not pass keyboard shortcuts in Incognito mode, and therefore global hotkeys do not apply. I'm not sure I'll be able to fix that within the extension, it *might* be a Chrome limitation.

One thing you can try is opening `chrome://extensions/shortcuts`, changing or adding a new key binding to eg. "shuffle", and see if that works any better.

**Comment by Zopieux** [comment]
Please reopen with additional feedback, closing for now. 🙂
