### ISSUE TITLE
advance song skips 1 song

### ISSUE THREAD

**Issue by matt-klotz** [Zopieux/spotify-hotkeys#5]
hi - i set my hotkey up as Alt+Shift+. to advance a spotify track. it defintely advances past the track that's supposed to follow. so it skips past a song right after using the key combo.

**Comment by Zopieux** [comment]
Hey,

I just tried it out and the binding successfully advances to the next track, without "skip over" the next track. Please check you're not sending it twice accidentally!

**Comment by matt-klotz** [comment]
you're right. i had at multiple tabs of Spotify open. i've closed a few so one remains and it's fine. TY
