### ISSUE TITLE
Add support for podcast 15 sec. skip

### ISSUE THREAD

**Issue by Architectuur** [Zopieux/spotify-hotkeys#6]
Is it possible to get support for a hotkey for the spotify podcast 15 sec skip?

**Comment by Zopieux** [comment]
Never tried the podcast feature, so I was not even aware of these :) Thanks for bringing this up.

v0.6.0 (418c703604053714aa39e11f30396b2e7c2a1a58) adds new shortcuts for Podcast seeking as well as other minor things. I did not add default bindings for them, you can add bindings in `chrome://extensions/shortcuts`.

v0.6.0 is being reviewed by Google right now, it should be available some time next week.
