### ISSUE TITLE
Toggle song like not working

### ISSUE THREAD

**Issue by jsauder2** [Zopieux/spotify-hotkeys#7]
The `toggle song like` shortcut hasn't been working over the last few months. I'm on a MacBook Pro (macOS 11.5.2), Chrome 92.0.4515.131, and extension version 0.6.0.

The play/pause and skip shortcuts still work. I've tried changing the global shortcut and restarting Chrome. I also have the same issue in Vivaldi.

**Comment by Zopieux** [comment]
Thanks, I'll have a look in the coming days.

**Comment by Zopieux** [comment]
Version 0.6.1 is out for review by Google.

**Comment by jsauder2** [comment]
Seems like this broke again (not sure when as I haven't been using Spotify until recently).

**Comment by zopieux** [comment]
@jsauder2 I just tried this minute and "song like" is working here. Please make sure you're using the right keyboard shortcut in `chrome://extensions/shortcuts`, try remapping it temporarily and restarting Chrome (`chrome://restart`).

**Comment by jsauder2** [comment]
You're right. I just wiped out the hotkey, restarted Chrome, reset the hotkey, restarted Chrome again, and now it's working. Sorry for the false alarm. Thanks again for fixing this. I've done a lot of searching, and you have the only resource to toggle liked songs on Spotify that actually works and doesn't involve macros/python/etc to get working.
