### ISSUE TITLE
Trigger actions outside the extension

### ISSUE THREAD

**Issue by raddup** [Zopieux/spotify-hotkeys#8]
Hi there :)

Is there a way to trigger each of the (play,shuffle,repeat,etc) on separately functions?

because i want to trigger each element only with javascript, outside.. chrome extensions..

**Comment by Zopieux** [comment]
I'm not sure I understand your question, each action already has its own key binding. Do you mean you'd like to be able to trigger actions not using keys but rather using some JS coming from somewhere else? You're free to extract the logic in `background.js`, but I don't see how I could make code changes to accommodate this in this extension.

Good luck!

**Comment by raddup** [comment]
> I'm not sure I understand your question, each action already has its own key binding. Do you mean you'd like to be able to trigger actions not using keys but rather using some JS coming from somewhere else? You're free to extract the logic in `background.js`, but I don't see how I could make code changes to accommodate this in this extension.
> 
> Good luck!

yes. i want to trigger actions with selenium and python, but i don't know what function is attributed to what key in the javascript, i don't understand very good background.js

**Comment by raddup** [comment]
> > I'm not sure I understand your question, each action already has its own key binding. Do you mean you'd like to be able to trigger actions not using keys but rather using some JS coming from somewhere else? You're free to extract the logic in `background.js`, but I don't see how I could make code changes to accommodate this in this extension.
> > Good luck!
> 
> yes. i want to trigger actions with selenium and python, but i don't know what function is attributed to what key in the javascript, i don't understand very good background.js

in my mind it has to be
function = action(repeat)
but i don't see how the actions are triggered..
