### ISSUE TITLE
Hotkeys work only for a while

### ISSUE THREAD

**Issue by sautin1** [zopieux/spotify-hotkeys#9]
The extension doesn't work correctly with the current version of Spotify Web Player.

When enabled (`Manage Extensions` / `Spotify Web Player Hotkeys` / Switch in the lower right corner) the extension works fine for a while, but after a few songs the player stops reacting to the hotkeys and the extension has to be manually disabled and reenabled to work again.

I refer only to those hotkeys:
- Play/Pause media key
- Previous media key
- Next media key

I didn't try using the other ones.

OS: Ubuntu 20.04.3 LTS (64 bit)
Chrome: 97.0.4692.71 (Official Build) (64-bit)
Spotify Web Player Hotkeys: 0.6.1

**Comment by zopieux** [comment]
Thanks for the bug report @sautin1 . I have trouble reproducing the issue though. What does "after a few songs" mean, do you have a more precise number of amount of time that one needs to wait for this to happen?

If not, may I ask that you open devtools (F12) at the beginning of a listening session (while the hotkeys are still working) and report back what the *Console* tab contains once the keys stop working?

**Comment by sautin1** [comment]
@zopieux
I am pretty sure the hotkeys stop working starting from the moment the first Spotify ad pops up.

I suspect that the problem is related to another extension I am using - [AdGuard Antibanner](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg), which prevents websites from showing ads (or just skips them in case of Spotify). The issue is present with AdGuard enabled, hovewer I could not reproduce it after I disabled AdGuard.

See contents of the console in the log attached.
[open.spotify.com-1642601759827.log](https://github.com/zopieux/spotify-hotkeys/files/7897770/open.spotify.com-1642601759827.log)

**Comment by zopieux** [comment]
I see, thanks. Sadly it is unreasonable for me to debug or change the code to be compatible with the wide variety of random extensions people might install alongside SWPHK, that might break SWPHK for various (obscure) reasons. I'm gonna have to close this "won't fix".
